framgialink: "https://www.facebook.com/FramgiaVietnam"
khanhlink: "http://www.facebook.com/khanhmata.dn"
nhatlink: "#"
nguyenlink: "https://www.facebook.com/thaonguyen.tran.7311352"
rubyrailslink: "http://www.railstutorial.org/"
nothing: "#"
pagination:
  per_page: 10
  size: 10
role:
  user: "User"
  admin: "Admin"
status:
  exam:
    start: "start"
    testing: "testing"
    uncheck: "uncheck"
    checked: "checked"
    inactive: "inactive"
exams:
  default_score: 0
  default_spent_time: 0
  default_correct: false
  notify_hour: 8
  notify_priority: 0
