framgialink: "https://www.facebook.com/FramgiaVietnam"
khanhlink: "http://www.facebook.com/khanhmata.dn"
nhatlink: "#"
nguyenlink: "https://www.facebook.com/thaonguyen.tran.7311352"
rubyrailslink: "http://www.railstutorial.org/"
nothing: "#"
minimum_suggest_answer: 1
minimum_answer: 1
reject_suggest_answer: 0
each_question: 1
each_user: 1
user_per_page: 10
pagination:
  per_page: 10
  size: 10
role:
  user: user
  admin: admin
status:
  exam:
    start: "start"
    testing: "testing"
    uncheck: "uncheck"
    checked: "checked"
    inactive: "inactive"
exams:
  default_score: 0
  default_spent_time: 0
  default_correct: false
  notify_hour: 8
  notify_priority: 0
questions:
  answer_type:
    single_choice: "single_choice"
    multi_choice: "multi_choice"
    text: "text"
suggest_questions:
  status:
    confirmed: "Approved"
    rejected: "Rejected"
